- name: mysql-apb playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    state: absent
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: rhscl-mysql-apb-openshift
    playbook_debug: false
