- name: mysql-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: rhscl-mysql-apb-openshift
    playbook_debug: false
