---
- name: create namespace if it does not exist
  openshift_v1_project:
    name: "{{ namespace }}"
  when: state == 'present'

- include: dev.yml
  when: plan == "dev"

- include: prod.yml
  when: plan == "prod"

- name: Set {{ service_name }} service state to {{ state }}
  k8s_v1_service:
    name: "{{ service_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: rhscl-mysql-apb
      service: "{{ service_name }}"
    selector:
      app: rhscl-mysql-apb
      service: "{{ service_name }}"
    ports:
    - name: mysql
      port: 3306
      target_port: 3306
    state: "{{ state }}"
  register: mysql_service

- name: encode bind credentials
  shell: 'echo "{\"MYSQL_HOST\": \"{{ mysql_service.service.spec.cluster_ip }}\", \"MYSQL_PORT\": \"3306\", \"MYSQL_USER\": \"{{ mysql_user }}\", \"MYSQL_PASSWORD\": \"{{ mysql_password }}\", \"MYSQL_DATABASE\": \"{{ mysql_database }}\"}" | base64 -w 0'
  register: encoded_bind_credentials
  when: state == 'present'

- name: save credentials
  copy:
    content: "<BIND_CREDENTIALS>{{ encoded_bind_credentials.stdout }}</BIND_CREDENTIALS>"
    dest: /etc/apb/bind-creds
  when: state == 'present'
